# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: snip.proto for package 'snip'

require 'grpc'
require 'snip_pb'

module Snip
  module UrlSnipService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'snip.UrlSnipService'

      rpc :snip_it, SnipRequest, SnipResponse
    end

    Stub = Service.rpc_stub_class
  end
end
